### ISSUE TITLE
Support video player?

### ISSUE THREAD

**Issue by opsopus** [sheikhhaziq/gyavun#46]
### Feature description

Hi there,
Would it be possible to add support video player? such as YouTube Music app

Maybe the implantation from pod_player, same package from youtube_explode_dart
https://github.com/newtaDev/pod_player

thanks and best

**Comment by sheikhhaziq** [comment]
I'll look into it and keep you updated

**Comment by opsopus** [comment]
> I'll look into it and keep you updated

I appreciate it.
