### ISSUE TITLE
Roatate screen

### ISSUE THREAD

**Issue by powl999** [sheikhhaziq/gyavun#54]
### Steps to reproduce the bug

Play a song open the music player turn your screen and then back to portrait and then the music player is bugging it stays on half the hight of the screen 
This also happens on Xiaomi then you switch between this floating apps to vibe music

### Expected behavior

It shouldn't be bugging out and stay at the half of screen 

### Actual behavior

It's bugging out and stay at half the hight of the screen 

### Vibe Music version

0.7.1

### Android version

Android 12

**Comment by sheikhhaziq** [comment]
problem with screen rotation has been fixed.
