### ISSUE TITLE
Adaptive Icon and Symmetricity

### ISSUE THREAD

**Issue by ayu2805** [sheikhhaziq/gyavun#68]
### Feature description

1. Please consider adding **adaptive icon** as it provides variety of shapes/masks across different device models. For example in pixel/AOSP based OS(i.e. many custom roms) the icon looks something like this.....which is pretty ugly.

![Screenshot_20230220-094036_Launcher3](https://user-images.githubusercontent.com/76616749/220008678-f6333413-fc73-4b0a-9f1d-2c2b38132438.png)

2. Also consider reviewing symmetricity in the UI. I found out that search bar is not symmetric at all like this.....its not symmetric to the thumbnails situated below which is not so attractive.

![01_2](https://user-images.githubusercontent.com/76616749/220012328-94ff03b1-2e15-4165-a0c5-989a628e8d94.jpg)

There r two ways to solve this issue:

I) Either **remove the search bar** and make it a search ion on the top left....like there will be a gap between searchicon and setings icon. And that gap can be used for placing the AppName
II) Or just **nuke the settings icon** and let the search bar cover all the space by moving the settings icon to the navigation bar below.

**Comment by sheikhhaziq** [comment]
adaptive icons have been added.
