### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Baker0o7** [sheikhhaziq/gyavun#77]
Hi thanks for your hardworking and beautiful app the last beta update not working it keeps  loading only

**Comment by sheikhhaziq** [comment]
What do you mean by loading only. Can you be more specific.

**Comment by Baker0o7** [comment]
![Screenshot_20230225-223714_Vibe Music_1](https://user-images.githubusercontent.com/113295927/221376426-d024f39c-163a-4521-bfce-f1dbf8b8be0f.png)

**Comment by Baker0o7** [comment]
It keeps  loading nothing shows up

**Comment by owencz1998** [comment]
Have u tried clearing data and cache

**Comment by Baker0o7** [comment]
Yes but still the same

**Comment by owencz1998** [comment]
Did the previous build work

**Comment by Baker0o7** [comment]
O.7.1 was  working fine newer version didn't work for me

**Comment by sheikhhaziq** [comment]
Which android version are you using

**Comment by Baker0o7** [comment]
12

**Comment by sheikhhaziq** [comment]
Can you open the app with internet turned off. It should show no internet error. Then turn on internet and click the try again button

![Screenshot_2023-02-27-01-49-54-876_com.webyte.vibe_music.beta.jpg](https://user-images.githubusercontent.com/41983383/221435032-e57e2c73-53e9-46f5-91b4-8c82372318ec.jpg)

**Comment by Baker0o7** [comment]
It worked thank you so much sir

**Comment by Baker0o7** [comment]
But when I try to change it to another country same thing happens again

**Comment by Baker0o7** [comment]
It open the home when you click on album it keeps loading

**Comment by owencz1998** [comment]
Could u try a vpn for like the UK or something please
