### ISSUE TITLE
Suggestions for improving song downloads

### ISSUE THREAD

**Issue by GET100PERCENT** [sheikhhaziq/gyavun#80]
### Feature description

1. Add the respective thumbnails while downloading the songs locally (similar to spotiflier).
2. The song now is downloaded in low qualities, which could be of medium quality. 
3. The downloading speed is very slow, which could be improved. 
    Love this app. Best of luck .

**Comment by sheikhhaziq** [comment]
The audio returned from ytmusic is not mp3. In order to add coverArt, we need to convert it into mp3. To do so, I need to use ffmpeg, which will increase apk size from 9 mb to 50 mbs.

**Comment by GET100PERCENT** [comment]
Then how spotiflier do this having the apk size equal to only 8.1 mb.
https://github.com/Shabinder/SpotiFlyer
![Screenshot_20230306-143154](https://user-images.githubusercontent.com/116144024/223064304-c2c15b5d-1b92-495f-95fe-f35ea750f752.jpg)

**Comment by sheikhhaziq** [comment]
I just switched from youtube music to jio Saavn. You can check it out
