### ISSUE TITLE
not an issue just asking

### ISSUE THREAD

**Issue by Ravan1190** [sheikhhaziq/gyavun#85]
i'm also creating an app for music streaming with more features. Inspired by vibemusic 

I just want to know how you made the hostaddress ? 

static String hostAddress = "https://vibeapi-sheikh-haziq.vercel.app/";

**Comment by sheikhhaziq** [comment]
I am used ytmusicapi from python and deployed it on vercel

**Comment by Ravan1190** [comment]
Can you share me the python code.
Please

**Comment by sheikhhaziq** [comment]
I am no longer using youtube music, I switched to Jio Saavn. If you wanna try Youtube Music, You can look at [Blackhole](https://github.com/Sangwan5688/BlackHole/blob/main/lib/Services/yt_music.dart)
